import { Label } from '../../src/components/index.types';

export const stockLabels: Label[] = [
  { title: 'ABM Industries Incorporated', count: 15 },
  { title: 'Archer-Daniels-Midland Company', count: 29, href: '#' },
  { title: 'Automatic Data Processing, Inc.', count: 48 },
  { title: 'Aflac Incorporated', count: 17 },
  { title: 'Albemarle Corporation', count: 34 },
  { title: 'A. O. Smith Corporation', count: 50, href: '#' },
  { title: 'Air Products and Chemicals, Inc.', count: 27 },
  { title: 'Arrow Financial Corporation', count: 34 },
  { title: 'Artesian Resources Corporation', count: 10 },
  { title: 'Atmos Energy Corporation', count: 21 },
  { title: 'AptarGroup, Inc.', count: 14, href: '#' },
  { title: 'American States Water Company', count: 49, href: '#' },
  { title: 'BancFirst Corporation', count: 18, href: '#' },
  { title: 'Becton, Dickinson and Company', count: 14 },
  { title: 'Franklin Resources, Inc.', count: 39 },
  { title: 'Brown-Forman Corporation', count: 35 },
  { title: 'Black Hills Corporation', count: 46, href: '#' },
  { title: 'Badger Meter, Inc.', count: 47 },
  { title: 'Brady Corporation', count: 2 },
  { title: 'Brown & Brown, Inc.', count: 19 },
  { title: 'Cardinal Health, Inc.', count: 11 },
  { title: 'Caterpillar Inc.', count: 33 },
  { title: 'Chubb Limited', count: 15 },
  { title: 'Commerce Bancshares, Inc.', count: 40, href: '#' },
  { title: 'Community Bank System, Inc.', count: 8 },
  { title: 'Cullen/Frost Bankers, Inc.', count: 29 },
  { title: 'Church & Dwight Co., Inc.', count: 15 },
  { title: 'Cincinnati Financial Corporation', count: 10 },
  { title: 'Colgate-Palmolive Company', count: 46, href: '#' },
  { title: 'The Clorox Company', count: 50, href: '#' },
  { title: 'Canadian National Railway Company', count: 19 },
  { title: 'Carlisle Companies Incorporated', count: 13 },
  { title: 'Cintas Corporation', count: 18 },
  { title: 'Community Trust Bancorp, Inc.', count: 6 },
  { title: 'Chevron Corporation', count: 43, href: '#' },
  { title: 'California Water Service Group', count: 21, href: '#' },
  { title: 'Donaldson Company, Inc.', count: 25 },
  { title: 'Dover Corporation', count: 25 },
  { title: 'Enterprise Bancorp, Inc.', count: 11 },
  { title: 'Ecolab Inc.', count: 47, href: '#' },
  { title: 'Consolidated Edison, Inc.', count: 4 },
  { title: 'Emerson Electric Co.', count: 2 },
  { title: 'Enbridge Inc.', count: 20 },
  { title: 'Erie Indemnity Company', count: 2 },
  { title: 'Essex Property Trust, Inc.', count: 75, href: '#' },
  { title: 'Eaton Vance Corp.', count: 6 },
  { title: 'Expeditors International of Washington, Inc.', count: 33 },
  { title: 'Franklin Electric Co., Inc.', count: 32 },
  { title: 'The First of Long Island Corporation', count: 46, href: '#' },
  { title: 'Federal Realty Investment Trust', count: 31 },
  { title: 'H.B. Fuller Company', count: 2 },
  { title: 'General Dynamics Corporation', count: 21 },
  { title: 'Genuine Parts Company', count: 40 },
  { title: 'W.W. Grainger, Inc.', count: 11 },
  { title: 'Hormel Foods Corporation', count: 99, href: '#' },
  { title: 'International Business Machines Corporation', count: 40, href: '#' },
  { title: 'Illinois Tool Works Inc.', count: 15 },
  { title: 'Jack Henry & Associates, Inc.', count: 34 },
  { title: 'Johnson & Johnson', count: 25 },
  { title: 'John Wiley & Sons, Inc.', count: 35 },
  { title: 'Kimberly-Clark Corporation', count: 4 },
  { title: 'The Coca-Cola Company', count: 41, href: '#' },
  { title: 'Lancaster Colony Corporation', count: 2 },
  { title: 'Lincoln Electric Holdings, Inc.', count: 3 },
  { title: 'Leggett & Platt, Incorporated', count: 89, href: '#' },
  { title: 'Linde plc', count: 25, href: '#' },
  { title: "Lowe's Companies, Inc.", count: 42, href: '#' },
  { title: 'Matthews International Corporation', count: 32 },
  { title: "McDonald's Corporation", count: 34 },
  { title: 'Mercury General Corporation', count: 29 },
  { title: 'Medtronic plc', count: 46 },
  { title: 'MDU Resources Group, Inc.', count: 45 },
  { title: 'MGE Energy, Inc.', count: 28 },
  { title: 'McGrath RentCorp', count: 31 },
  { title: 'McCormick & Company, Incorporated', count: 14 },
  { title: '3M Company', count: 27 },
  { title: 'MSA Safety Incorporated', count: 6 },
  { title: 'Nordson Corporation', count: 91, href: '#' },
  { title: 'NextEra Energy, Inc.', count: 26 },
  { title: 'National Fuel Gas Company', count: 37 },
  { title: 'New Jersey Resources Corporation', count: 36 },
  { title: 'National Retail Properties, Inc.', count: 43, href: '#' },
  { title: 'Nucor Corporation', count: 15 },
  { title: 'Northwest Natural Holding Company', count: 18, href: '#' },
  { title: 'Realty Income Corporation', count: 28 },
  { title: 'Old Republic International Corporation', count: 36 },
  { title: 'Bank OZK', count: 1 },
  { title: "People's United Financial, Inc.", count: 20 },
  { title: 'PepsiCo, Inc.', count: 48, href: '#' },
  { title: 'The Procter & Gamble Company', count: 26, href: '#' },
  { title: 'Parker-Hannifin Corporation', count: 6 },
  { title: 'Polaris Inc.', count: 23 },
  { title: 'PPG Industries, Inc.', count: 7 },
  { title: 'RLI Corp.', count: 37, href: '#' },
  { title: 'RenaissanceRe Holdings Ltd.', count: 43 },
  { title: 'Roper Technologies, Inc.', count: 10 },
  { title: 'RPM International Inc.', count: 37, href: '#' },
  { title: 'Raytheon Technologies Corporation', count: 14 },
  { title: 'Southside Bancshares, Inc.', count: 6, href: '#' },
  { title: 'Stepan Company', count: 19 },
  { title: 'SEI Investments Company', count: 15 },
  { title: 'The Sherwin-Williams Company', count: 64, href: '#' },
  { title: 'SJW Group', count: 35 },
  { title: 'Sonoco Products Company', count: 34, href: '#' },
  { title: 'S&P Global Inc.', count: 4 },
  { title: '1st Source Corporation', count: 28, href: '#' },
  { title: 'Stanley Black & Decker, Inc.', count: 4 },
  { title: 'Stryker Corporation', count: 29 },
  { title: 'Sysco Corporation', count: 26, href: '#' },
  { title: 'AT&T Inc.', count: 19 },
  { title: 'Telephone and Data Systems, Inc.', count: 9 },
  { title: 'Target Corporation', count: 11 },
  { title: 'First Financial Corporation', count: 24, href: '#' },
  { title: 'Tompkins Financial Corporation', count: 32, href: '#' },
  { title: 'Tennant Company', count: 13 },
  { title: 'Thomson Reuters Corporation', count: 22 },
  { title: 'T. Rowe Price Group, Inc.', count: 4 },
  { title: 'United Bankshares, Inc.', count: 32, href: '#' },
  { title: 'UGI Corporation', count: 46, href: '#' },
  { title: 'Universal Health Realty Income Trust', count: 75, href: '#' },
  { title: 'UMB Financial Corporation', count: 45, href: '#' },
  { title: 'Universal Corporation', count: 11 },
  { title: 'Westamerica Bancorporation', count: 47, href: '#' },
  { title: 'Walgreens Boots Alliance, Inc.', count: 16, href: '#' },
  { title: 'Weyco Group, Inc.', count: 47 },
  { title: 'Walmart Inc.', count: 13 },
  { title: 'West Pharmaceutical Services, Inc.', count: 85 },
  { title: 'Essential Utilities, Inc.', count: 47, href: '#' },
  { title: 'Exxon Mobil Corporation', count: 35, href: '#' }
];
